### PR TITLE
Laravel 5.5 support

### PR DESCRIPTION
**Pull request by royduin**

### CODE REVIEW

**Comment by royduin** [comment]
Please merge 👼

**Comment by gbs** [comment]
I asked them to reactivate my credentials again. Will upgrade asap after I'm able to test again.

**Comment by royduin** [comment]
Any updates? Using my fork in projects now...

**Comment by gbs** [comment]
Hi Roy, I have been quite busy past weeks. I'll pick it up next week.

**Comment by JoeyHoutenbos** [comment]
Hi @gbs ,

Can you please merge this so we have Laravel 5.6 support?

**Comment by gbs** [comment]
Hi guys,

Sorry it took so long, but through private matters I could not find the energy. Anyway, thanks for your support and for using this package. v4.0 is available now and tests are passing.

**Pull request closed without merging**
